portapp/urls.py
from django.urls import path
from portapp import views
from django.contrib.auth import views as auth_views
from portapp.models import * 

app_name = 'portapp'

urlpatterns=[
    path('blog/', views.blog, name='blog'),
    path('blog-detail/<int:pk>', views.BlogDetail, name='blog_detail'),
    path('register/', views.regform, name='reg'),
    path('login/', views.login_user, name='login'),
    
    

]

portfolio_project/urls.py
from django.contrib import admin
from django.urls import path, include
from portapp import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('portapp/', include('portapp.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('dashboard/', include('dashboard.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

portapp/models.py
from django.db import models
from django.contrib.auth.models import User

from tinymce.models import HTMLField

# Create your models here.
class Education(models.Model):
    year = models.IntegerField()
    title = models.CharField(max_length = 50)
    description = models.TextField()
    
class Contact(models.Model):
    name = models.CharField(max_length = 20)
    email = models.EmailField()
    vemail = models.EmailField()
    phone_no = models.IntegerField()
    message = models.TextField()

    def __str__(self):
     return self.name

class Blog(models.Model):
    image = models.ImageField(null=True, blank=True)
    title = models.CharField(max_length=30)
    created_on = models.DateTimeField(auto_now_add=True)
    description =  HTMLField()
    title2 = HTMLField()
    poster = models.ForeignKey(User, null=True, on_delete=models.CASCADE)

    def image_url(self):
        if self.image:
            return self.image.url


    def __str__(self):
        return self.title              


class Comment(models.Model):
    post = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length= 50)
    email = models.EmailField()
    comment = models.TextField()
    created = models.DateTimeField(auto_now_add= True)
    updated = models.DateTimeField(auto_now= True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f'comment by {self.name} on {self.post}'

class Register(models.Model):
    username = models.ForeignKey(User, on_delete=models.CASCADE)
    firstname = models.CharField(max_length=20)
    lastname = models.CharField(max_length=20)
    password = models.IntegerField()
    vpassword = models.IntegerField()
    email = models.CharField(max_length=20)

    def __str__(self):
        return self.firstname

portapp/forms.py
from django import forms
from portapp.models import *
from django.core import validators
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class ContactForm(forms.ModelForm):
    
    name = forms.CharField(widget=forms.TextInput(attrs={'class':'form_control','placeholder':'Your Name', 'style':'width:100%'}))
    email= forms.EmailField(widget=forms.EmailInput(attrs={'class':'form_control', 'placeholder':'Your Email', 'style':'width:100%'}))
    vemail= forms.CharField(widget=forms.EmailInput(attrs={'class':'form_control','placeholder':'Re-enter email', 'style':'width:100%'}))
    phone_no = forms.CharField(widget=forms.TextInput(attrs={'class':'form_control','placeholder':'Your Phone_no', 'style':'width:100%'}))
    message=forms.CharField(widget=forms.Textarea(attrs={'class':'form_control','placeholder':'Message', 'style':'width:100%'}))
    botcatcher = forms.CharField(required=False, widget=forms.HiddenInput,validators=[validators.MaxLengthValidator(0)])
    class Meta():
        model = Contact
        fields = '__all__'



    def clean(self):
        cleaned_data = super().clean()
        email = cleaned_data.get('email')
        vemail = cleaned_data.get('vemail')
        
        if email != vemail:
            raise forms.ValidationError('Your emails must match')

class CommentForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control', 'style':'width:100%'}))
    email= forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control', 'style':'width:100%'}))
    comment= forms.CharField(widget=forms.Textarea(attrs={'class':'form-control', 'placeholder':'comment', 'style':'width:100%'}))
    class Meta():
        model =Comment 
        fields = ('name', 'email', 'comment')

class RegForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control p-3', 'placeholder':'Username', 'style':'width:90%'}))
    first_name= forms.CharField(widget=forms.TextInput(attrs={'class':'form-control p-3','placeholder':'Firstname', 'style':'width:90%'}))
    last_name= forms.CharField(widget=forms.TextInput(attrs={'class':'form-control p-3', 'placeholder':'Lastname', 'style':'width:90%'}))
    password1= forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control p-3', 'placeholder':'Input Password', 'style':'width:90%'}))
    password2= forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control p-3', 'placeholder':'Re-enter password', 'style':'width:90%'}))
    email= forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control p-3','placeholder':'Email', 'style':'width:90%'}))
    botcatcher = forms.CharField(required=False, widget=forms.HiddenInput,validators=[validators.
    MaxLengthValidator(0)])
    
              

    class Meta():
        model = User
        fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2']     
       

    def clean(self):
        cleaned_data = super().clean()
        password1 = cleaned_data.get('password1')
        password2 = cleaned_data.get('password2')
        
        if password1 != password2:
            raise forms.ValidationError('passwords must match')

        

portapp/views.py
from urllib import request
from django.shortcuts import render, redirect,get_object_or_404
from django.http import HttpResponse
from portapp.models import *
from portapp.forms import *
from django.contrib import messages
from django.core import validators
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login

def blog(request):
    blog = Blog.objects.all()
    return render(request, 'portapp/blog.html', {'blog':blog})

# def blog_detail(request):
#     return render(request, 'portapp/blog_detail.html') 
# class BlogDetail(DetailView):
#     model =Blog
#     template_name = 'portapp/blog_detail.html' 
#     context_object_name = 'blog_detail' 

def BlogDetail(request, pk):
    blog_detail = get_object_or_404(Blog, pk=pk)
    comments = Comment.objects.filter(post__pk=pk).order_by('-created')
    most_recent = Blog.objects.order_by()[:3]
    if request.method == 'POST':
        comm = CommentForm(request.POST, request.FILES)
        if comm.is_valid():
            new_comment = comm.save(commit=False)
            new_comment.post = blog_detail
            new_comment.save()
            return redirect('portapp:blog_detail', pk=blog_detail.pk)
    else:
        comm = CommentForm()
   

    return render(request, 'portapp/blog_detail.html', {'comm':comm, 'comments':comments,'blog_detail':blog_detail, 'most_recent':most_recent})
     

    
def index(request):
    education = Education.objects.all()
    if request.method =="POST":
        cform = ContactForm(request.POST)
        if cform.is_valid():
            cform.save()
    else:
        cform = ContactForm()        
    return render(request, 'portapp/home.html', {'education':education, 'cform':cform})

def regform(request):
    if request.method =='POST':
        form = RegForm(request.POST)
        if form.is_valid():
            user=form.save()
            messages.success(request, 'successfully created')
            return redirect('portapp:login')
    else:
        form = RegForm()
        
    return render(request,'portapp/reg.html', {'reg':form})     

def login_user (request):
    if request.method=='POST':
        username = request.POST['username']
        password= request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('dashboard:dashboard')  
            messages.info(request, f'welcome to the dashboard {{user.username}}')     
    else:
        return render (request, 'portapp/login.html')





        

templates/portapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>{% block title %}
        {% endblock %}
  </title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'portapp/assets/img/favicon.png' %}" rel="icon">
  <link href="{% static 'portapp/assets/img/apple-touch-icon.png'%}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Satisfy" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'portapp/assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'portapp/assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'portapp/assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'portapp/assets/vendor/glightbox/css/glightbox.min.css'%}" rel="stylesheet">
  <link href="{% static 'portapp/assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'portapp/assets/css/style.css'%} " rel="stylesheet">
</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top d-flex justify-content-center align-items-center header-transparent">

    <nav id="navbar" class="navbar fixed-top">
      <ul>
        <li><a class="nav-link scrollto active" href="{%url 'index' %}">Home</a></li>
        <li><a class="nav-link scrollto" href="#about">About</a></li>
        <li><a class="nav-link scrollto" href="#resume">Resume</a></li>
        <li><a class="nav-link scrollto" href="#services">Services</a></li>
        <li><a class="nav-link scrollto " href="#portfolio">Portfolio</a></li>
        <li><a class="nav-link scrollto" href="#contact">Contact</a></li>
        <li><a class="nav-link scrollto" href="{% url 'portapp:blog' %}">Blog</a></li>
        <li><a class="nav-link scrollto" href="{% url 'portapp:login' %}">Login</a></li>
      </ul>
        
      <i class="bi bi-list mobile-nav-toggle"></i>
    </nav><!-- .navbar -->

  </header><!-- End Header -->
  {% block content %}
  {% endblock%}
  

  <!-- footer starts -->
  <footer id="footer">
    <div class="container">
      <h3>Joan Izuka</h3>
      <p>That's what we do for a living and we look forward to making more attractive websites for your firms.</p>
      <div class="social-links">
        <a href="https://twitter.com/Awelejojo" class="twitter"><i class="bx bxl-twitter"></i></a>
        <a href="https://web.facebook.com/joan.izuka.5" class="facebook"><i class="bx bxl-facebook"></i></a>
        <a href="https://wa.me/23409035636964" class="whatsapp"><i class="bx bxl-whatsapp"></i></a>
        
      </div>
      <div class="copyright">
        &copy; Copyright <strong><span>Joan</span></strong>. All Rights Reserved
      </div>
      <div class="credits">
        
      </div>
    </div>
  </footer><!-- End Footer -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'portapp/assets/vendor/purecounter/purecounter.js' %}"></script>
  <script src="{% static 'portapp/assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'portapp/assets/vendor/glightbox/js/glightbox.min.js'%}"></script>
  <script src="{% static 'portapp/assets/vendor/isotope-layout/isotope.pkgd.min.js'%}"></script>
  <script src="{% static 'portapp/assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'portapp/assets/vendor/waypoints/noframework.waypoints.js' %}"></script>
  <script src="{% static 'portapp/assets/vendor/php-email-form/validate.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'portapp/assets/js/main.js' %}"></script>

</body>

</html>

templates/portapp/blog.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  

  <title>{% block title %}
        {% endblock %}
  </title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'portapp/assets/img/favicon.png' %}" rel="icon">
  <link href="{% static 'portapp/assets/img/apple-touch-icon.png'%}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Satisfy" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'portapp/assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'portapp/assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'portapp/assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'portapp/assets/vendor/glightbox/css/glightbox.min.css'%}" rel="stylesheet">
  <link href="{% static 'portapp/assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'portapp/assets/css/style.css'%} " rel="stylesheet">
</head>
<body>
  

<section id="hero">
  <div class="hero-container">
    <h1>My Page</h1>
    
</section><!-- End Hero -->

<section id="portfolio" class="portfolio"  style="background-color: burlywood;">
  <div class="container">

    <div class="section-title">
      <span class="blog">Welcome to my Blog</span>
      <h2>joan's Blog</h2>
      <p>Welcome to my page which brings information and understanding of things happening around us..Stay tunned</p>
    </div>


    <div class="row portfolio-container">
      {% if blog %}
      {% for b in blog %}
      <div class="col-lg-4 col-md-6 portfolio-item filter-card">
        <div class="portfolio-img"><img src="{{b.image_url}}" style="max-width: 300px;min-width: 300px; 
          max-height: 300px; min-height: 300px;" class="img-fluid" alt=""></div>
        <div class="portfolio-info">
          <h3><a href="{% url 'portapp:blog_detail' b.id%}" >{{b.title}}</a></h3>
          <p>{{b.description|truncatewords:30|safe}}</p>
          <!-- <a href="{% static 'portapp/assets/img/portfolio/portfolio-4.jpg'%}" data-gallery="portfolioGallery" class="portfolio-lightbox preview-link" title="Card 2"><i class="bx bx-plus"></i></a>
          <i class="bx bx-link"></i></a> -->
        </div>
      </div>
      {% endfor %}
      {% endif %}
  
     

    </div>

  </div>
</section><!-- End My blog Section -->


  <!-- footer starts -->
  <footer id="footer">
    <div class="container">
      <h3>Joan Izuka</h3>
      <p>That's what we do for a living and we look forward to making more attractive websites for your firms.</p>
      <div class="social-links">
        <a href="https://twitter.com/Awelejojo" class="twitter"><i class="bx bxl-twitter"></i></a>
        <a href="https://web.facebook.com/joan.izuka.5" class="facebook"><i class="bx bxl-facebook"></i></a>
        <a href="https://wa.me/23409035636964" class="whatsapp"><i class="bx bxl-whatsapp"></i></a>
        
      </div>
      <div class="copyright">
        &copy; Copyright <strong><span>Joan</span></strong>. All Rights Reserved
      </div>
      <div class="credits">
        
      </div>
    </div>
  </footer><!-- End Footer -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'portapp/assets/vendor/purecounter/purecounter.js' %}"></script>
  <script src="{% static 'portapp/assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'portapp/assets/vendor/glightbox/js/glightbox.min.js'%}"></script>
  <script src="{% static 'portapp/assets/vendor/isotope-layout/isotope.pkgd.min.js'%}"></script>
  <script src="{% static 'portapp/assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'portapp/assets/vendor/waypoints/noframework.waypoints.js' %}"></script>
  <script src="{% static 'portapp/assets/vendor/php-email-form/validate.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'portapp/assets/js/main.js' %}"></script>

</body>

</html>

  

templates/portapp/blog_detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
  <link href="{% static 'portapp/assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'portapp/assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'portapp/assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'portapp/assets/vendor/glightbox/css/glightbox.min.css'%}" rel="stylesheet">
  <link href="{% static 'portapp/assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">
    <!-- Template Main CSS File -->
    <link href="{% static 'portapp/assets/css/style.css'%} " rel="stylesheet">
</head>
<body>
    <section>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-sm-4">
            <h1 style="font-style: italic;">Blog Detail
            </h1>
              <span class="bg-danger">Metro</span>
              <h1>{{blog_detail.title2|safe}}</h1>
              <p style="font-style: italic;" ></p>
              
              
              <img src="{{blog_detail.image_url}}"  class="img-fluid image-res" alt="">
              <p class="offset-5">{{blog_detail.created_on}}</p>
              <h3>{{blog_detail.title}} </h3>
              <p>{{blog_detail.description|safe}}</p>
             

          </div>
          <div class="col-lg-2 col-sm-6  pt-5 offset-2 most ">
            <!-- <h4>Search</h4>
            <div >
              <input type="text" class="form-control" placeholder="Search for..." aria-label="Search for...">
              <div class="bg-danger" style="margin-left: 167px; position: absolute; top: 90px;" ><button inputmode="submit"><i class="bi bi-search"></i></div></button> -->
            
              <h3>Most Recent</h3> 
              <ul>
                {% if most_recent %}
                {% for m in most_recent %}
                <li>
                  <img src="{{m.image.url}}" width="100" alt="">
                  <a href="{% url 'portapp:blog_detail' m.id %}">{{m.title}}</a>
                </li>
                {% endfor %}
                {% endif %}

              </ul>
               
            
            
             
            

          </div>        
        </div>
      </div>          
    </section>
    <div class="container">
      <h3>Your View</h3>
        {% with comments.count as total_comments%}
        <h2>
          {{total_comments}} comments {{total_comments|pluralize}}
        </h2>
        {% endwith%}
        {% for c in comments%}
        <div>
          <p class="info">
            {{c.name}} {{c.created}}
            
          </p>
          {{c.comment|linebreaks}}
          {% empty%}
          <p>There are no comments yet</p>
          {% endfor%}
          {% if new_comment%}
          <p>Your comment has been saved</p>
          {% else %}
          <h2>Add your Comment</h2>
  
            <div class="form  p-3 mt-3 bg-danger">
              <form action="" method="post"  >
                {{ comm.as_p }}
                {% csrf_token %}
                <button class="btn btn-light">POST</button>
                <!-- <p><input type="submit" value="Post"></p> -->
              </form>
  
            </div>
          
          {% endif %}
  
         
        
  
      </div>
      

    </div>
    

    </div>
      <div class="col-md-6">
      

      
        
    
            
      </section><!-- End Blog Single Section -->
      <script src="{% static 'portapp/assets/vendor/purecounter/purecounter.js' %}"></script>
      <script src="{% static 'portapp/assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
      <script src="{% static 'portapp/assets/vendor/glightbox/js/glightbox.min.js'%}"></script>
      <script src="{% static 'portapp/assets/vendor/isotope-layout/isotope.pkgd.min.js'%}"></script>
      <script src="{% static 'portapp/assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
      <script src="{% static 'portapp/assets/vendor/waypoints/noframework.waypoints.js' %}"></script>
      <script src="{% static 'portapp/assets/vendor/php-email-form/validate.js' %}"></script>
    
</body>
</html>

templates/portapp/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="{% static 'portapp/assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'portapp/assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'portapp/assets/font-awesome-4.5.0/css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'portapp/assets/css/style.css'%} " rel="stylesheet">
</head>
<style>
    #username{
        border-radius: 20px;
    }
    #email{border-radius: 20px;}
    #password{border-radius: 20px;}
    #btn{width:30%;}

</style>
<body style="background-color:wheat;"  >
    <div class="container bg-light p-5 log" style="margin-top: 80px;" >
        <div class ="mt-3">
            <div><h2 class="offset-2 account">Log In to your account!</h2></div>
        <form action="" method="post">
            <i class="bi bi-person"></i>
            <input type="text" id="username" name="username" placeholder="Enter your username" class="p-3 mt-3 w-100"><br>
    
            <i class="fa fa-lock"></i>
            <input type="password" id="password" placeholder="Create Password" name="password" class="p-3 mt-3 w-100"><br>
            
            {% csrf_token %}
            <div class="mt-3">
                <button type="submit" class="bg-danger p-2 button"  id="btn" >LOGIN</button>
                <!-- <button type="submit">Log In </button> -->
                <p class="offset-5">Don't have an account? <a href="{% url 'portapp:reg'%}">create an account.</a></p>
    
    
            </div>
            
    
        </div>
        
    
        </form>
    </div>
    

    
</body>
</html>

templates/portapp/reg.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="{% static 'portapp/assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'portapp/assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'portapp/assets/css/style.css'%} " rel="stylesheet">
</head>
<style>
    body{
        background-color: brown;
    }
    .container{
        /* background-color: aliceblue; */
    }
</style>
<body>
    <div class= " container mt-3 pb-2 reg">
        <div >
            <h2 class="offset-2 text-secondary pt-3 h2" style="font-style:italic;">Create an account!</h2>
        <form action="" method="post"class="offset-1 pt-3">
            {% if messages %}
            {% for m in messages %}
            <div class="alert alert-danger">{{m}}</div>
            {% endfor %}
            {% endif %}
            {{reg.username}}<br>
            {{reg.email}}<br>
            {{reg.first_name}}<br>
            {{reg.last_name}}<br>
            {{reg.password1}}<br>
            {{reg.password2}}
            {% csrf_token %}
            <button class="bg-danger p-2 w-25" type="submit">Enter</button> <br>
            <p class="offset-5 mt-3">Already have an account?<a href="{% url 'portapp:login'  %}">Sign In</a></p>
             
    
        </form>
    
        </div>

    </div>
    
    
</body>
</html>