dashboard/urls.py
from django.urls import path
from dashboard import views
from dashboard.forms import *


app_name ='dashboard'

urlpatterns =[
    path('dashboard/', views.dash, name='dashboard'),
    path('login/', views.log, name='login'),
    path('addblog/', views.addblog, name='addblog'),
    path('viewblog/', views.viewblog, name='viewblog'),
    path('changepassword/', views.passwordview, name='changepassword'),
    path('profile/', views.profilepage, name='profile'),
    path('editprofile/', views.edit_profile, name='editprofile'),
    path('editpost/<int:pk>', views.edit_post, name='editpost'),
    path('viewpost/<int:pk>', views.view_post, name='viewpost'),
    path('delete/<int:pk>', views.delete_post, name='delete'),
    path('logout/', views.logout_request, name='logout')
    

]

portapp/urls.py
from django.urls import path
from portapp import views
from django.contrib.auth import views as auth_views
from portapp.models import * 

app_name = 'portapp'

urlpatterns=[
    path('blog/', views.blog, name='blog'),
    path('blog-detail/<int:pk>', views.BlogDetail, name='blog_detail'),
    path('register/', views.regform, name='reg'),
    path('login/', views.login_user, name='login'),
    
    

]

portfolio_project/urls.py
from django.contrib import admin
from django.urls import path, include
from portapp import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('portapp/', include('portapp.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('dashboard/', include('dashboard.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

dashboard/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Profile(models.Model):
    user= models.OneToOneField(User,  null=True, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='uploads/pics')
    

    def __str__(self):
        return f'{self.user.username} Profile'

dashboard/forms.py
from django import forms
from django.core import validators
from django.contrib.auth.models import User
from portapp.models import Blog
from django.contrib.auth.forms import PasswordChangeForm, UserCreationForm
from dashboard.models import *

class AddBlog(forms.ModelForm):
    title =forms.CharField(max_length=20, widget=forms.TextInput(attrs={'class':'form-control','style':'width:60%'}))
    description =forms.CharField(max_length=20, widget=forms.Textarea(attrs={'class':'form-control','style':'width:60%'}))
    class Meta():
        model = Blog
        exclude = ['title2', 'poster']

    
class ChangePasswordForm(PasswordChangeForm):
    old_password = forms.CharField(widget=forms.PasswordInput(attrs = {'class':'form-control', 'type':'password', 'style':'width:60%'})) 
    new_password1 = forms.CharField(widget= forms.PasswordInput(attrs={'class':'form-control', 'type':'password', 'style':'width:60%'})) 
    new_password2 = forms.CharField(widget= forms.PasswordInput(attrs={'class':'form-control', 'type':'password', 'style':'width:60%'}))
    class Meta():
        model = User
        fields = ('old_password', 'new_password1', 'new_password2')


class EditUserForm(forms.ModelForm):
    username =forms.CharField(max_length=20, widget=forms.TextInput(attrs={'class':'form-control','style':'width:60%'}))
    first_name =forms.CharField(max_length=20, widget=forms.TextInput(attrs={'class':'form-control','style':'width:60%'}))
    last_name =forms.CharField(max_length=20, widget=forms.TextInput(attrs={'class':'form-control','style':'width:60%'}))
    email =forms.CharField(max_length=20, widget=forms.TextInput(attrs={'class':'form-control','style':'width:60%'}))
    
    class Meta():
        model = User
        fields = ['username', 'first_name', 'last_name','email']
        exclude = ['password']
        
class EditBlogForm(forms.ModelForm):
    class Meta():
        model = Blog
        exclude=['poster']

dashboard/views.py
from django.shortcuts import render, redirect,get_object_or_404
from dashboard.forms import *
from portapp.models import Blog
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib import messages
from django.contrib.auth.decorators import login_required



# Create your views here.
def dash(request):
    return render(request, 'dashboard/dashboard.html')
def log(request):
    return render(request,'dashboard/login.html') 
def addblog(request):
    if request.method=='POST':
        blog = AddBlog(request.POST, request.FILES)
        if blog.is_valid():
            blog.save()
            return redirect('dashboard:viewblog')
            messages.success(request,'Blog posted')
            
    else:
        blog = AddBlog()
    return render(request, 'dashboard/addblog.html', {'Blog':blog}) 

def passwordview(request):
    if request.method=='POST':
        form = ChangePasswordForm(data=request.POST, user=request.user)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            messages.success(request, 'Password changed successfully')
    else:
        form = ChangePasswordForm(user=request.user)
    return render(request, 'dashboard/changepassword.html', {'form_key':form})


def profilepage(request):
    return render(request, 'dashboard/profile.html')        
    
def edit_profile(request):
    if request.method=='POST':
        p_form = EditUserForm(request.POST, instance=request.user)
        if p_form.is_valid():
            p_form.save()
            messages.success(request, f'your account has been updated!')
            # return redirect('dashboard:profile')
    else:
        p_form = EditUserForm(instance=request.user)
    
    context ={
        'p_form':p_form
    }             
    return render(request, 'dashboard/editprofile.html',context)

# @login_required(login_url='user:login')
def viewblog(request):
    view_blog = Blog.objects.filter(poster=request.user)
    return render(request, 'dashboard/viewblog.html', {'view':view_blog})  
         
# for the view blog of the dashboard i.e edit,delete and view
def edit_post(request, pk):
    editblog =get_object_or_404(Blog, pk=pk)
    if request.method =='POST':
        editblog = EditBlogForm(request.POST, request.FILES, instance=editblog)
        if editblog.is_valid():
            editblog.save()
            return redirect('dashboard:viewblog') 
            mesages.success(request, 'successful')                     
    else:
        editblog = EditBlogForm(instance=editblog)
    return render(request, 'dashboard/editpost.html',{'edit':editblog})

def view_post(request,pk):
    post = get_object_or_404(Blog, pk=pk)
    return render(request, 'dashboard/viewpost.html', {'post':post}) 
    return redirect('dashboard:viewblog') 

def delete_post(request,pk):
    record= get_object_or_404(Blog, pk=pk)
    record.delete()
    return redirect('dashboard:viewblog')

def logout_request(request):
    logout(request)
    messages.success(request, 'You have successfully logged out.') 
    return redirect('index')   

templates/dashboard/addblog.html
{% extends 'dashboard/base.html' %}
{% load static %}
{% block title %}
{% endblock %}

{% block content %}
                   
                     <form action="" method="post" enctype="multipart/form-data">
                        {% if messages %}
                        {% for m in messages %}
                        <div class="alert alert-success">{{m}}</div>
                        {% endfor %}
                        {% endif %}
                        {{Blog.as_p}}
                        {% csrf_token%}
                        <button type="submit" class="btn btn-outline-success">Post </button>
                    </form>
{% endblock %}                  

templates/dashboard/base.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
   <head>
      <!-- basic -->
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <!-- mobile metas -->
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta name="viewport" content="initial-scale=1, maximum-scale=1">`
      <!-- site metas -->
      <title>My dashboard page</title>
      <meta name="keywords" content="">
      <meta name="description" content="">
      <meta name="author" content="">
      <!-- site icon -->
      <link rel="icon" href="{% static 'dashboard/images/fevicon.png' %}" type="image/png" /> 
      <!-- bootstrap css -->
      <link rel="stylesheet" href="{% static 'dashboard/css/bootstrap.min.css' %}" />
      <!-- site css -->
      <link rel="stylesheet" href="{% static 'dashboard/css/style.css' %}" />
      <!-- responsive css -->
      <link rel="stylesheet" href="{% static 'dashboard/css/responsive.css' %}" />
      <!-- color css -->
      <link rel="stylesheet" href="{% static 'dashboard/css/colors.css' %}" />
      <!-- select bootstrap -->
      <link rel="stylesheet" href="{% static 'dashboard/css/bootstrap-select.css' %}" />
      <!-- scrollbar css -->
      <link rel="stylesheet" href="{% static 'dashboard/css/perfect-scrollbar.css' %}" />
      <!-- custom css -->
      <link rel="stylesheet" href="{% static 'dashboard/css/custom.css' %}" />
   </head>
   <body class="dashboard dashboard_1">
      <div class="full_container">
         <div class="inner_container">
            <!-- Sidebar  -->
            <nav id="sidebar">
               <div class="sidebar_blog_1">
                  <div class="sidebar-header">
                     <div class="logo_section">
                        <!-- <a href="{% url 'portapp:blog'%}"><img class="logo_icon img-responsive" src="{% static 'dashboard/images/logo/logo_icon.png'%}" alt="#" /></a> -->
                     </div>
                  </div>
                  <div class="sidebar_user_info">
                     <div class="icon_setting"></div>
                     <div class="user_profile_side">
                        <div class="user_img"><img class="img-responsive" src="images/layout_img/user_img.jpg"  /></div>
                        <div class="user_info">
                           <h6>welcome {{request.user.get_username}}</h6>
                           <p><span class="online_animation"></span> Online</p>
                        </div>
                     </div>
                  </div>
               </div>
               <div class="sidebar_blog_2">
                  <h4>General</h4>
                  <ul class="list-unstyled components">
                     <li class="active">
                        <a href="{% url 'dashboard:dashboard'%}"><span>Dashboard</span></a>
                     </li>
                     
                     <li class="dropdown">
                        <a href="#" data-toggle="dropdown" aria-expanded="false" class="dropdown-toggle"><span>Blogs</span></a>
                        <ul class=" dropdown-menu" id="Blogs">
                           <li>
                              <a class="dropdown-item" href="{% url 'dashboard:viewblog' %}"><span>View Blog</span></a>
                           </li>

                           <li>
                              <a class="dropdown-item" href="{% url 'dashboard:addblog' %}"><span>Add Blog</span></a>
                           </li>

                        </ul>
                     </li>
                     
                  
                     <li class="dropdown">
                        <a href="#" data-toggle="dropdown" class="dropdown-toggle" aria-expanded="false"> <span>Profile</span></a>
                        <ul class="dropdown-menu">
                           <li><a class="dropdown-item" href="{% url 'dashboard:profile' %}">View profile</a></li>
                           <li><a class="dropdown-item" href="{% url 'dashboard:editprofile' %}">Edit profile</a></li>
                           <li><a class="dropdown-item" href="{% url 'dashboard:changepassword' %}">Change password</a></li>

                        </ul>
                     </li>
                  </ul>
               </div>
            </nav>
            <!-- end sidebar -->
            <!-- right content -->
            <div id="content">
               <!-- topbar -->
               <div class="topbar">
                  <nav class="navbar navbar-expand-lg navbar-light">
                     <div class="full">
                        <button type="button" id="sidebarCollapse" class="sidebar_toggle"><i class="fa fa-bars"></i></button>
                        <div class="logo_section">
                           <a href="{% url 'portapp:blog'%}"><img class="img-responsive" src="{% static 'dashboard/images/logo/logo.png' %}" alt="#" /></a>
                        </div>
                        <div class="right_topbar">
                           <div class="icon_info">
                             
                              <ul class="user_profile_dd">
                                 <li>
                                    <a class="dropdown-toggle" data-toggle="dropdown"><img class="img-responsive rounded-circle" src="{% static 'dashboard/images/layout_img/user_img.jpg'%}" alt="#" /><span class="name_user">{{request.user.get_full_name}}</span></a>
                                    <div class="dropdown-menu">
                                       <a class="dropdown-item" href="{% url 'dashboard:profile'%}">My Profile</a>
                                       <a class="dropdown-item" href="{% url 'dashboard:changepassword'%}">settings</a>
                                       <a class="dropdown-item" href="{% url 'dashboard:logout'%}"><span>Log Out</span></a>
                                    

                                    </div>
                                 </li>
                              </ul>
                           </div>
                        </div>
                     </div>
                  </nav>
               </div>
               <!-- end topbar -->
               <!-- dashboard inner -->
               <div class="midde_cont">
                  <div class="container-fluid">
                     <div class="row column_title">
                        <div class="col-md-12">
                           <div class="page_title">
                              <h2>Dashboard</h2>
                           </div>
                        </div>
                     </div>
                   {% block content%}
                   {% endblock %}
                  <!-- footer -->
                  <div class="container-fluid">
                     <div class="footer">
                        <p> Designed by <strong>Snazzzy 'J'</strong>. All rights reserved.<br><br>
                        
                        </p>
                     </div>
                  </div>
               </div>
               <!-- end dashboard inner -->
            </div>
         </div>
      </div>
      <!-- jQuery -->
      <script src="{% static 'dashboard/js/jquery.min.js' %}"></script>
      <script src="{% static 'dashboard/js/popper.min.js' %}"></script>
      <script src="{% static 'dashboard/js/bootstrap.min.js' %}"></script>
      <!-- wow animation -->
      <script src="{% static 'dashboard/js/animate.js'%}"></script>
      <!-- select country -->
      <script src="{% static 'dashboard/js/bootstrap-select.js'%}"></script>
      <!-- owl carousel -->
      <script src="{% static 'dashboard/js/owl.carousel.js'%}"></script> 
      <!-- chart js -->
      <script src="{% static 'dashboard/js/Chart.min.js'%}"></script>
      <script src="{% static 'dashboard/js/Chart.bundle.min.js'%}"></script>
      <script src="{% static 'dashboard/js/utils.js'%}"></script>
      <script src="{% static 'dashboard/js/analyser.js'%}"></script>
      <!-- nice scrollbar -->
      <script src="{% static 'dashboard/js/perfect-scrollbar.min.js'%}"></script>
      <script>
         var ps = new PerfectScrollbar('#sidebar');
      </script>
      <!-- custom js -->
      <script src="{% static 'dashboard/js/chart_custom_style1.js'%}"></script>
      <script src="{% static 'dashboard/js/custom.js'%}"></script>
   </body>
</html>

templates/dashboard/changepassword.html
{% extends 'dashboard/base.html' %}
{% load static %}
{% block title %}
{% endblock %}

{% block content %}
<div>
    <form action="" method="post">
        {% if messages %}
        {% for m in messages %}
        <div class="alert alert-success">{{m}}</div>
        {% endfor %}
        {% endif %}
        {{form_key.as_p}}
        {% csrf_token %}
        <button>submit</button>
    </form>
    
</div>
{% endblock %}

templates/dashboard/editpost.html
{% extends 'dashboard/base.html' %}
{% load static %}
{% block title %}
{% endblock %}

{% block content %}
    <div>
        <form action="" method="post">
            {% if messages %}
            {% for m in messages %}
            <div class="alert alert-success">{{m}}</div>
            {% endfor %}
            {% endif %}
            {{edit.as_p}}
            {% csrf_token %}
            <button class="btn btn-outline-danger">POST</button>
            
        </form>
    </div>
    
{% endblock %}

templates/dashboard/editprofile.html
{% extends 'dashboard/base.html' %}
{% load static %}
{% block title %}
{% endblock %}

{% block content %}
<div class="container">
    <form action="" method="post" enctype="multipart/form-data">
        {% if messages %}
        {% for m in messages %}
        <div class="alert alert-success">{{m}}</div>
        {% endfor %}
        {% endif %}
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Profile Info</legend>
           
            {{p_form.as_p}}
        </fieldset>
        <button class="btn btn-outline-info">Update</button>
    
    
    </form>
    
    
</div>



{% endblock %}

templates/dashboard/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
   <head>
      <!-- basic -->
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <!-- mobile metas -->
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta name="viewport" content="initial-scale=1, maximum-scale=1">
      <!-- site metas -->
      <title>Pluto - Responsive Bootstrap Admin Panel Templates</title>
      <meta name="keywords" content="">
      <meta name="description" content="">
      <meta name="author" content="">
      <!-- site icon -->
      <link rel="icon" href="{% static 'dashboard/images/fevicon.png'%}" type="image/png" />
      <!-- bootstrap css -->
      <link rel="stylesheet" href="{% static 'dashboard/css/bootstrap.min.css'%}" />
      <!-- site css -->
      <link rel="stylesheet" href="{% static 'dashboard/css/style.css'%}" />
      <!-- responsive css -->
      <link rel="stylesheet" href="css/responsive.css" />
      <!-- color css -->
      <link rel="stylesheet" href="css/colors.css" />
      <!-- select bootstrap -->
      <link rel="stylesheet" href="css/bootstrap-select.css" />
      <!-- scrollbar css -->
      <link rel="stylesheet" href="css/perfect-scrollbar.css" />
      <!-- custom css -->
      <link rel="stylesheet" href="css/custom.css" />
      <!-- calendar file css -->
      <link rel="stylesheet" href="js/semantic.min.css" />
      <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
      <![endif]-->
   </head>
   <body class="inner_page login">
      <div class="full_container">
         <div class="container">
            <div class="center verticle_center full_height">
               <div class="login_section">
                  <div class="logo_login">
                     <div class="center">
                        <img width="210" src="{% static 'dashboard/images/logo/logo.png' %}" alt="#" />
                     </div>
                  </div>
                  <div class="login_form">
                     <form>
                        <fieldset>
                           <div class="field">
                              <label class="label_field">Email Address</label>
                              <input type="email" name="email" placeholder="E-mail" />
                           </div>
                           <div class="field">
                              <label class="label_field">Password</label>
                              <input type="password" name="password" placeholder="Password" />
                           </div>
                           <div class="field">
                              <label class="label_field hidden">hidden label</label>
                              <label class="form-check-label"><input type="checkbox" class="form-check-input"> Remember Me</label>
                              <a class="forgot" href="">Forgotten Password?</a>
                           </div>
                           <div class="field margin_0">
                              <label class="label_field hidden">hidden label</label>
                              <button class="main_bt">Sing In</button>
                           </div>
                        </fieldset>
                     </form>
                  </div>
               </div>
            </div>
         </div>
      </div>
      <!-- jQuery -->
      <script src="{% static 'dashboard/js/jquery.min.js'%}"></script>
      <script src="{% static 'dashboard/js/popper.min.js'%}"></script>
      <script src="{% static 'dashboard/js/bootstrap.min.js'%}"></script>
      <!-- wow animation -->
      <script src="{% static 'dashboard/js/animate.js'%}"></script>
      <!-- select country -->
      <script src="{% static 'dashboard/js/bootstrap-select.js'%}"></script>
      <!-- nice scrollbar -->
      <script src="js/perfect-scrollbar.min.js"></script>
      <script>
         var ps = new PerfectScrollbar('#sidebar');
      </script>
      <!-- custom js -->
      <script src="js/custom.js"></script>
   </body>
</html>

templates/dashboard/profile.html
{% extends 'dashboard/base.html' %}
{% load static %}
{% block title %}
{% endblock %}

{% block content %}
               <!-- end topbar -->
               <!-- dashboard inner -->
               <div class="midde_cont">
                  <div class="container-fluid">
                     <div class="row column_title">
                        <div class="col-md-12">
                           <div class="page_title">
                              <h2>Profile</h2>
                           </div>
                        </div>
                     </div>
                     <!-- row -->
                     <div class="row column1">
                        <div class="col-md-2"></div>
                        <div class="col-md-8">
                           <div class="white_shd full margin_bottom_30">
                              <div class="full graph_head">
                                 <div class="heading1 margin_0">
                                    <h2>User profile</h2>
                                 </div>
                              </div>

                           </div>         
                             

                              
                              
                              <!-- <div class="full price_table padding_infor_info">
                                 <div class="row">
                                    user profile section  -->
                                    <!-- profile image -->
                                   
                                       <!-- end user profile section -->
                                    </div>
                                 </div>
                              </div>
                           </div>
                        
                        </div>
                        <!-- end row -->
                     </div>
                  

                     <div class="row">
                        <div class="col-md-3 " enctype="multipart/form-data">
                           <img class="offset-5 rounded-circle" width="100" src="../../media/uploads/pics/joan.jpg" alt="">
                        </div>
                        <div class="col-md-4 ">
                           <h2>{{user.username}}</h2> <br>
                           <h2>{{user.first_name}}</h2> <br>
                           <h2>{{user.last_name}}</h2><br>
                           <h4>{{user.email}}</h4>

                        </div>

                     </div>   
                  
{% endblock %}                 

templates/dashboard/viewblog.html
{% extends 'dashboard/base.html' %}
{% load static %}
{% block title%}
{% endblock %}

{% block content%}



 <h2>View Blog</h2> <br>

 <div class="row">
  <table class="table table-bordered">
   <tr>
    <th>S/N</th>
    <th>Post Title</th>
    <th>Post Content</th>
    <th>Post Image</th>
    <th>Action</th>
   </tr>
   {% if view %}
   {% for v in view %}

   <tr>
     <td>{{ forloop.counter}}</td>
     <td>{{ v.title}}</td>
     <td>{{v.description|truncatewords:20|safe}}</td>
     <td><img width="70" src="{{ v.image_url }}" alt=""></td>
     <td>
       <a href="{% url 'dashboard:viewpost' v.id %}">View</a>
     </td>
     <td>
       <a href="{% url 'dashboard:delete' v.id %}">Delete</a>
     </td>
     <td>
       <a href="{% url 'dashboard:editpost' v.id %}">Edit</a>
     </td>
   </tr>
 
{% endfor %}
{% endif %}

  </table>
{% endblock %}

templates/dashboard/viewpost.html
{% extends 'dashboard/base.html' %}
{% load static %}
{% block title %}
{% endblock %}

{% block content %}
<body>
    <div>
        <h2>View Posts</h2><br><br>
        <h3>{{post.title}}</h3><br>
        <img src="{{post.image_url}}" class="img-fluid w-50 h-50" alt="">
        <p>{{post.description}}</p>
    </div>
    <button><a href="{% url 'dashboard:viewblog'%}">Back</a></button>
{% endblock %}